name: Spellcheck Action

on:
  push:
    paths:
    - '**.md'
    - '.github/workflows/check-spelling.yml'
    - '.github/spellcheck.yml'
    - '.github/spellchecker-wordlist.txt'

permissions: read-all

jobs:
  build:
    name: Spellcheck
    runs-on: ubuntu-latest
    steps:

    - name: Harden Runner
      uses: step-security/harden-runner@ab7a9404c0f3da075243ca237b5fac12c98deaa5 # v2.19.3
      with:
        egress-policy: block
        allowed-endpoints: >
          github.com:443

    - name: Check out repository
      uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

    - name: Spellcheck
      uses: rojopolis/spellcheck-github-actions@e3cd8e9aec4587ec73bc0e60745aafd45c37aa2e # 0.60.0
      with:
        config_path: .github/spellcheck.yml # put path to configuration file here
