name: Spellcheck Action

on:
  push:
    paths:
    - '**.md'
    - '.github/workflows/check-spelling.yml'
    - '.github/spellcheck.yml'
    - '.github/spellchecker-wordlist.txt'

permissions: read-all

jobs:
  build:
    name: Spellcheck
    runs-on: ubuntu-latest
    steps:

    - name: Harden Runner
      uses: step-security/harden-runner@b09bb98e06d4d774595224525879c09bc6e98c40 # v2.20.1
      with:
        egress-policy: block
        allowed-endpoints: >
          github.com:443

    - name: Check out repository
      uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      with:
        persist-credentials: false

    - name: Spellcheck
      uses: rojopolis/spellcheck-github-actions@fcc5ca8351f0590978f238d6babfe3f28afc361f # 0.65.0
      with:
        config_path: .github/spellcheck.yml # put path to configuration file here
